version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
      MYSQL_ROOT_PASSWORD: chat
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: chat
      MONGO_INITDB_ROOT_PASSWORD: chat
      MONGO_INITDB_DATABASE: chat
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

  app:
    image: ankyeongeun/chat-and-pay:latest
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - mongo
    volumes:
      - ./logs:/app/logs
